blank_issues_enabled: false
contact_links:
  - name: Public support not yet available
    url: https://github.com/akalynth/akalynth-site
    about: This repository is not currently accepting public support requests.
